### ISSUE TITLE
Visuals for F# Compiler Technical Overview

### ISSUE THREAD

**Issue by sergey-tihon** [fsharp/fsharp.github.io#39]
Would be nice to have high-level diagram of compiler components for http://fsharp.github.io/2015/09/29/fsharp-compiler-guide.html
or processing pipeline (something like that)

I think that it will be much easier to understand with some visuals.

**Comment by dsyme** [comment]
Yes please :)

**Comment by sergey-tihon** [comment]
WoW! Thank you @dungpa !
