### ISSUE TITLE
Give a simple summary of coding conventions

### ISSUE THREAD

**Issue by smoothdeveloper** [fsharp/fsharp.github.io#59]
The codebase is sizable and contains many conventions that are implicit to the main maintainers.

To keep codebase consistent with increasing number of contributors and help convey this currently implicit knowledge with code review, it would be great to have a short summary of:
- conventions in places
- where they apply
- design choices about code being written in such and such way
- things that prescribed / avoided
- ... whatever comes to mind of maintainers to share

**Comment by dsyme** [comment]
See https://docs.microsoft.com/en-us/dotnet/fsharp/style-guide/conventions
