### ISSUE TITLE
String comparison

### ISSUE THREAD

**Issue by ales004** [fsharp/fsharp.github.io#66]
Hi,
I am not sure that this is the right place where to post this problem. I have noticed that the string comparison seems to work somehow differently than expected.

We had a couple of problems because writing string1 = string2 was returning false also if strings were equal. The only way to solve this problem is by writing string1.Equals(string2).
Is it because of what described [here](https://blogs.msdn.microsoft.com/dsyme/2009/11/08/equality-and-comparison-constraints-in-f/)? Maybe the structural comparison for strings is comparing object references?

In my opinion this is a bug as it is highly non intuitive... or I am doing something wrong?

Regards,
Alessandro Seganti

**Comment by sishtiaq** [comment]
Can you post a small test case?

**Comment by dsyme** [comment]
Yes, please post an issue at http://github.com/Microsoft/visualfsharp, with full repro steps.
