### ISSUE TITLE
Update whole documentation and content

### ISSUE THREAD

**Issue by realvictorprm** [fsharp/fsharp.github.io#79]
Hello fellows,

it's time that we or rather I should start updating the whole documentation and content here as much as possible. Seeing what happened the last 2 years until now there are relevant topics which changed.

@dsyme, @ReedCopsey after talking about the future of the _Core Engineering Group_ it's crucial to know whether it's still valid here.

It will take some time to point out what's incorrect and or missing. I'm collecting relevant information here and also ask for help if questions come up.

PS: I think of refactoring and cleanup too

Update, Todo List is provided down here:

- [ ] Delete not necessary branches
- [ ] Check build system
- [ ] Discuss further using name  "Core Engineering Group"

**Comment by realvictorprm** [comment]
Speaking of cleanup, sorry for telling you but are those branches really needed @dsyme?

**Comment by dsyme** [comment]
> Speaking of cleanup, sorry for telling you but are those branches really needed @dsyme?

None of the branches are needed

**Comment by dsyme** [comment]
Closing this old issue (though it's true this content all needs updating)
