### ISSUE TITLE
Add information about how to setup to use the NuGet commands

### ISSUE THREAD

**Issue by ShalokShalom** [fsharp/fsharp.github.io#81]
This page lacks any information about how to setup a project and that this is necessary in order to use Nuget. 

![screenshot_20171011_135611](https://user-images.githubusercontent.com/6344099/31439377-38f7c1a8-ae8c-11e7-8171-fef001d37c54.png)

**Comment by ShalokShalom** [comment]
All you get is a confusing error message. |> (.NET CLI)

**Comment by ReedCopsey** [comment]
This is an issue for the NuGet gallery, and has nothing to do with F#. Please report there: https://github.com/NuGet/NuGetGallery

**Comment by ShalokShalom** [comment]
This is correct. Thanks for fixing my exhaustion mistake. ;)
