### ISSUE TITLE
Talks about portable libs

### ISSUE THREAD

**Issue by haf** [fsharp/fsharp.github.io#84]
https://fsharp.github.io/2015/04/18/fsharp-core-notes.html#making-pcl-portable-libraries talks about portable libraries; should it? Feels like it should talk about .Net Core libs nowadays.

**Comment by dsyme** [comment]
Yes, we need to revise these sections (or delete them, pointing to canonical Microsoft documentation instead) and archive the older material.

**Comment by dsyme** [comment]
I've revised these now, thanks
