### ISSUE TITLE
The section on FSharp.Core references needs to be looked at

### ISSUE THREAD

**Issue by baronfel** [fsharp/fsharp.github.io#85]
https://fsharp.github.io/2015/04/18/fsharp-core-notes.html#fsharpcore-entries-in-project-files

Especially with regards to the new Sdk Projects, where there is an implicit FSharp.Core reference, no TargetFSharpCoreVersion, and BindingRedirects are no longer a thing in .Net Core world (IIRC).

Should this section remove these topics, and perhaps add some more around the implicit versions in the SDK?

**Comment by Porges** [comment]
From what I can tell, with the new tooling, projects will _always_ consume the package via nuget, and not from the GAC or anywhere else.

So if we're making a library we should have FSharp.Core as a dependency, and then everything will work nicely. (In fact, Paket is generating warnings if we don't reference FSharp.Core.)


Is that all correct?

**Comment by dsyme** [comment]
I'll revise this now

**Comment by dsyme** [comment]
See this PR - https://github.com/fsharp/fsharp.github.io/pull/86

**Comment by Porges** [comment]
Thanks!
